int main () {
  try
  {
    int total = 0;
	for (i=0;i<4;i++){ total++;}
	for( int i = 0; i < 4; i++ ) {
		total++;
		cout << "total incremente"<<i<<"fois" << endl;
		
	}
	cout << total << endl;

  }
  catch (int e)
  {
    cout << "An exception occurred. Exception Nr. " << e <<endl;
  }
  return 0;
}
